sudo: required
language: node_js
node_js:
  - "9"
services:
  - docker

before_install:
  # login to docker registry
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

install:
  - yarn install

script:
  - yarn linter
  - yarn test:ci
  - yarn build:docker

deploy:
  provider: script
  script: docker push unqpdes/todo-list-back
  on:
    branch: dockerized

